### ISSUE TITLE
Metric Deviation?

### ISSUE THREAD

**Issue by bmurauer** [WittleWolfie/PyGram#2]
Hi,
I was reading the paper linked in your description and noticed a deviation in the way you calculate the normalized distance.
While in the paper, the distance is calculated as:
`(union - 2 * intersect) / (union - intersect)`,
which can be rewritten as 
`1 - (intersect / union - intersect)`,
your implementation uses
`1 - 2 * (intersect / union)`,
which yields a different result. Do you have any explanation for this behavior?

**Comment by WittleWolfie** [comment]
Hi,

Cool to see interest in this project, it was a fun one :) I wrote that a
very long time ago and haven't really touched it/used it since then. It's
very possible there are bugs in the implementation, and I don't really
remember if this was intentional or not (probably not).

-Tyler

**Comment by bmurauer** [comment]
Hi,

OK thanks! I'll let you know if we have established any substantial results using your library and maybe I'll make a fork to test my attributions.

Great work, otherwise!
